#reactor
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:0b,id:"minecraft:firework_charge",Count:8b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:1b,id:"minecraft:firework_charge",Count:8b,tag:{Explosion:{Colors:[I;8978176]},display:{Name:"§aUranium Ingot"}},Damage:0s},{Slot:2b,id:"minecraft:firework_charge",Count:8b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:3b,id:"minecraft:obsidian",Count:16b,Damage:0s},{Slot:4b,id:"minecraft:skull",Count:1b,tag:{SkullOwner:{Id:"00000000-0000-0000-ee69-000000000020"},display:{Name:"§eAdvanced Machine Frame"}},Damage:3s},{Slot:5b,id:"minecraft:obsidian",Count:16b,Damage:0s},{Slot:6b,id:"minecraft:firework_charge",Count:8b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:7b,id:"minecraft:iron_block",Count:4b,Damage:0s},{Slot:8b,id:"minecraft:firework_charge",Count:8b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4b,id:"minecraft:skull",Count:1b,tag:{SkullOwner:{Id:"206a8059-f5fb-41e7-8b33-233b5c72f932",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2ZhZjNlZmJmZjZkN2VmNDY1ZWNhY2JjNTE3ZjRkYWQ1Y2MxYTIyNjFlYTdhNjA5ZjIxNmFhZTQ4Nzg0In19fQ=="}]}},display:{Name:"§4Fission Reactor Core",Lore:["§fBoils water around the reactor into steam.","§fCareful! Explodes if it overheats."]}},Damage:3s}]}

#turbine
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:0b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s},{Slot:1b,id:"minecraft:hopper",Count:8b,Damage:0s},{Slot:2b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s},{Slot:3b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s},{Slot:4b,id:"minecraft:skull",Count:1b,tag:{SkullOwner:{Id:"00000000-0000-0000-ee69-000000000018"},display:{Name:"§fBasic Machine Frame"}},Damage:3s},{Slot:5b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s},{Slot:6b,id:"minecraft:firework_charge",Count:4b,tag:{Explosion:{Type:0b,Colors:[I;16772611]},display:{Name:"§eConductive Alloy"}},Damage:0s},{Slot:7b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s},{Slot:8b,id:"minecraft:firework_charge",Count:4b,tag:{Explosion:{Type:0b,Colors:[I;16772611]},display:{Name:"§eConductive Alloy"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4b,id:"minecraft:skull",Count:1b,tag:{SkullOwner:{Id:"a2264edb-7dd6-460a-9826-6d6bd9f30bbf",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGQ4YjUxZGM5NTljMzNjMjUxNWJhZDY1ODk5N2Y2Y2VlOWY4NmRmMGU3ODdiNmM2ZjhkNTA3MDY0N2JkYyJ9fX0="}]}},display:{Name:"§4Steam Turbine",Lore:["§fConverts steam from reactors into energy.","§fProduces 24 kJ/steam"]}},Damage:3s}]}

#hazmat
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:0b,id:"minecraft:leather_helmet",Count:1b,Damage:0s},{Slot:1b,id:"minecraft:firework_charge",Count:4b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:2b,id:"minecraft:leather_leggings",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:leather_chestplate",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:firework_charge",Count:4b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:5b,id:"minecraft:leather_boots",Count:1b,Damage:0s},{Slot:6b,id:"minecraft:firework_charge",Count:4b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:7b,id:"minecraft:dye",Count:16b,Damage:11s},{Slot:8b,id:"minecraft:firework_charge",Count:4b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:0,id:leather_helmet,Count:1,Damage:1,tag:{Unbreakable:1,ench:[{id:1,lvl:2},{id:3,lvl:2}],display:{Name:"§eHazmat Suit",Lore:["§aRadiation Protection"],color:11449138}}},{Slot:2,id:leather_chestplate,Count:1,Damage:1,tag:{Unbreakable:1,ench:[{id:1,lvl:2},{id:3,lvl:2}],display:{Name:"§eHazmat Suit",Lore:["§aRadiation Protection"],color:11449138}}},{Slot:3,id:leather_leggings,Count:1,Damage:1,tag:{Unbreakable:1,ench:[{id:1,lvl:2},{id:3,lvl:2}],display:{Name:"§eHazmat Suit",Lore:["§aRadiation Protection"],color:11449138}}},{Slot:5,id:leather_boots,Count:1,Damage:1,tag:{Unbreakable:1,ench:[{id:1,lvl:2},{id:3,lvl:2}],display:{Name:"§eHazmat Suit",Lore:["§aRadiation Protection"],color:11449138}}}]}