#tinker table
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:0b,id:"minecraft:stained_glass",Count:4b,Damage:13s},{Slot:1b,id:"minecraft:diamond",Count:2b,tag:{ench:[{lvl:1,id:48}],display:{Name:"§3Crystal Composite"}},Damage:0s},{Slot:2b,id:"minecraft:stained_glass",Count:4b,Damage:13s},{Slot:3b,id:"minecraft:glowstone",Count:8b,Damage:0s},{Slot:4b,id:"minecraft:skull",Count:1b,tag:{SkullOwner:{Id:"00000000-0000-0000-ee69-000000000020"},display:{Name:"§eAdvanced Machine Frame"}},Damage:3s},{Slot:5b,id:"minecraft:glowstone",Count:8b,Damage:0s},{Slot:6b,id:"minecraft:iron_block",Count:4b,Damage:0s},{Slot:7b,id:"minecraft:firework_charge",Count:8b,tag:{Explosion:{Type:0b,Colors:[I;16772611]},display:{Name:"§eConductive Alloy"}},Damage:0s},{Slot:8b,id:"minecraft:iron_block",Count:4b,Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4b,id:"minecraft:skull",Count:1b,tag:{SkullOwner:{Id:"719b952b-6a23-49a8-90af-4b4ae854030b",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWRjMzA2MGNmNzUyNGFlM2ViNGRmZDJiNTg5ODAzOTVkMjNmN2UzNjk1NTE0MTU0YjFlNGE4MGQyOWM5ZjNmIn19fQ=="}]}},display:{Name:"§aTinkering Table",Lore:["§fUsed to put special modifiers on weapons and armor."]}},Damage:3s}]}

#charge pad
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:0b,id:"minecraft:redstone_block",Count:8b,Damage:0s},{Slot:1b,id:"minecraft:quartz_block",Count:16b,Damage:0s},{Slot:2b,id:"minecraft:redstone_block",Count:8b,Damage:0s},{Slot:3b,id:"minecraft:firework_charge",Count:4b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:4b,id:"minecraft:skull",Count:1b,tag:{SkullOwner:{Id:"00000000-0000-0000-ee69-000000000020"},display:{Name:"§eAdvanced Machine Frame"}},Damage:3s},{Slot:5b,id:"minecraft:firework_charge",Count:4b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:6b,id:"minecraft:iron_block",Count:4b,Damage:0s},{Slot:7b,id:"minecraft:firework_charge",Count:16b,tag:{Explosion:{Type:0b,Colors:[I;16772611]},display:{Name:"§eConductive Alloy"}},Damage:0s},{Slot:8b,id:"minecraft:iron_block",Count:4b,Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4b,id:"minecraft:skull",Count:1b,tag:{SkullOwner:{Id:"551d5e4a-a877-8fe7-c964-2acb77d25a31",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmM0MTlhNDRjNWI5NjdmNDczMTZkMWJlZDNjYzYzMmJkZWQxOTlhNWMzNDIxMTc5MWM3MGY5OThmZGJkNiJ9fX0="}]}},display:{Name:"§3Player Charging Pad",Lore:["§fStand on charge pad to charge internal player energy."]}},Damage:3s}]}

#gun part - barrel
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:0b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:1b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:2b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:6b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:7b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:8b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:stick,Count:1,tag:{ench:[{id:48,lvl:1}],display:{Name:"Gun Barrel",Lore:["A gun part."]}}}]}

#gun part - trigger
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:0b,id:"minecraft:planks",Count:4b},{Slot:1b,id:"minecraft:planks",Count:4b},{Slot:2b,id:"minecraft:planks",Count:4b},{Slot:3b,id:"minecraft:planks",Count:4b},{Slot:5b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s},{Slot:6b,id:"minecraft:planks",Count:4b},{Slot:8b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;6710886]},display:{Name:"§8Steel Ingot"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:stone_button,Count:1,tag:{ench:[{id:48,lvl:1}],display:{Name:"Trigger",Lore:["A gun part."]}}}]}

#gun part - stock
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:0b,id:"minecraft:wool",Count:4b},{Slot:1b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;8883115]},display:{Name:"§9Structual Alloy"}},Damage:0s},{Slot:3b,id:"minecraft:wool",Count:4b},{Slot:5b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;8883115]},display:{Name:"§9Structual Alloy"}},Damage:0s},{Slot:6b,id:"minecraft:wool",Count:4b},{Slot:7b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;8883115]},display:{Name:"§9Structual Alloy"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:wool,Count:1,tag:{ench:[{id:48,lvl:1}],display:{Name:"Stock",Lore:["A gun part."]}}}]}

#gun part - chamber
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:0b,id:"minecraft:firework_charge",Count:1b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s},{Slot:2b,id:"minecraft:firework_charge",Count:1b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s},{Slot:3b,id:"minecraft:firework_charge",Count:1b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s},{Slot:5b,id:"minecraft:firework_charge",Count:1b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s},{Slot:6b,id:"minecraft:firework_charge",Count:1b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s},{Slot:7b,id:"minecraft:firework_charge",Count:1b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s},{Slot:8b,id:"minecraft:firework_charge",Count:1b,tag:{Explosion:{Type:0b,Colors:[I;16750848]},display:{Name:"§cBronze Ingot"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:dropper,Count:1,tag:{ench:[{id:48,lvl:1}],display:{Name:"Magazine Chamber",Lore:["A gun part."]}}}]}

#gun - Rifle
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:3b,id:"minecraft:wool",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Stock"}},Damage:0s},{Slot:4b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:stick",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Gun Barrel"}},Damage:0s},{Slot:6b,id:"minecraft:dropper",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Magazine Chamber"}},Damage:0s},{Slot:7b,id:"minecraft:stone_button",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Trigger"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:carrot_on_a_stick,Count:1,Damage:1,tag:{Unbreakable:1,display:{Name:"§1Rifle"}}}]}

#gun - flame thrower
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:3b,id:"minecraft:wool",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Stock"}},Damage:0s},{Slot:4b,id:"minecraft:netherrack",Count:16b,Damage:0s},{Slot:5b,id:"minecraft:stick",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Gun Barrel"}},Damage:0s},{Slot:6b,id:"minecraft:dropper",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Magazine Chamber"}},Damage:0s},{Slot:7b,id:"minecraft:stone_button",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Trigger"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:carrot_on_a_stick,Count:1,Damage:3,tag:{Unbreakable:1,display:{Name:"§6Flame Thrower"}}}]}

#gun - sniper rifle
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:3b,id:"minecraft:wool",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Stock"}},Damage:0s},{Slot:4b,id:"minecraft:gold_block",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:stick",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Gun Barrel"}},Damage:0s},{Slot:6b,id:"minecraft:dropper",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Magazine Chamber"}},Damage:0s},{Slot:7b,id:"minecraft:stone_button",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Trigger"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:carrot_on_a_stick,Count:1,Damage:4,tag:{Unbreakable:1,display:{Name:"§8Sniper Rifle"}}}]}

#gun - pistol
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:3b,id:"minecraft:wool",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Stock"}},Damage:0s},{Slot:4b,id:"minecraft:iron_ingot",Count:4b,Damage:0s},{Slot:5b,id:"minecraft:stick",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Gun Barrel"}},Damage:0s},{Slot:6b,id:"minecraft:dropper",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Magazine Chamber"}},Damage:0s},{Slot:7b,id:"minecraft:stone_button",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Trigger"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:carrot_on_a_stick,Count:1,Damage:5,tag:{Unbreakable:1,display:{Name:"§1Pistol"}}}]}

#gun - rocket launcher
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:3b,id:"minecraft:wool",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Stock"}},Damage:0s},{Slot:4b,id:"minecraft:tnt",Count:8b,Damage:0s},{Slot:5b,id:"minecraft:stick",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Gun Barrel"}},Damage:0s},{Slot:6b,id:"minecraft:dropper",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Magazine Chamber"}},Damage:0s},{Slot:7b,id:"minecraft:stone_button",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Trigger"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:carrot_on_a_stick,Count:1,Damage:6,tag:{Unbreakable:1,display:{Name:"§cRocket Launcher"}}}]}

#gun - smg
#execute @s ~ ~ ~ testforblock ~ ~1 ~ minecraft:dispenser 1 {Items:[{Slot:3b,id:"minecraft:wool",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Stock"}},Damage:0s},{Slot:4b,id:"minecraft:repeater",Count:8b,Damage:0s},{Slot:5b,id:"minecraft:stick",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Gun Barrel"}},Damage:0s},{Slot:6b,id:"minecraft:dropper",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Magazine Chamber"}},Damage:0s},{Slot:7b,id:"minecraft:stone_button",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Trigger"}},Damage:0s}]}
#execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~1 ~ {Items:[{Slot:4,id:carrot_on_a_stick,Count:1,Damage:9,tag:{Unbreakable:1,display:{Name:"§8SMG"}}}]}

#### Tier 2 Weapons ####
#gun part - laser barrel
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:0b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;16772611]},display:{Name:"§eConductive Alloy"}},Damage:0s},{Slot:1b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;16772611]},display:{Name:"§eConductive Alloy"}},Damage:0s},{Slot:2b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;16772611]},display:{Name:"§eConductive Alloy"}},Damage:0s},{Slot:3b,id:"minecraft:diamond",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Name:"§3Crystal Composite"}},Damage:0s},{Slot:4b,id:"minecraft:diamond",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Name:"§3Crystal Composite"}},Damage:0s},{Slot:5b,id:"minecraft:diamond",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Name:"§3Crystal Composite"}},Damage:0s},{Slot:6b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;16772611]},display:{Name:"§eConductive Alloy"}},Damage:0s},{Slot:7b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;16772611]},display:{Name:"§eConductive Alloy"}},Damage:0s},{Slot:8b,id:"minecraft:firework_charge",Count:2b,tag:{Explosion:{Type:0b,Colors:[I;16772611]},display:{Name:"§eConductive Alloy"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:stick,Count:1,tag:{ench:[{id:48,lvl:2}],display:{Name:"Laser Gun Barrel",Lore:["A gun part."]}}}]}

#gun - laser drill
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:3b,id:"minecraft:wool",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Stock"}},Damage:0s},{Slot:4b,id:"minecraft:diamond",Count:4b,Damage:0s},{Slot:5b,id:"minecraft:stick",Count:1b,tag:{ench:[{lvl:2,id:48}],display:{Lore:["A gun part."],Name:"Laser Gun Barrel"}},Damage:0s},{Slot:6b,id:"minecraft:dropper",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Magazine Chamber"}},Damage:0s},{Slot:7b,id:"minecraft:stone_button",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Trigger"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:carrot_on_a_stick,Count:1,Damage:2,tag:{Unbreakable:1,display:{Name:"§4Laser Drill"}}}]}

#gun - laser rifle
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:3b,id:"minecraft:wool",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Stock"}},Damage:0s},{Slot:4b,id:"minecraft:emerald",Count:8b,Damage:0s},{Slot:5b,id:"minecraft:stick",Count:1b,tag:{ench:[{lvl:2,id:48}],display:{Lore:["A gun part."],Name:"Laser Gun Barrel"}},Damage:0s},{Slot:6b,id:"minecraft:dropper",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Magazine Chamber"}},Damage:0s},{Slot:7b,id:"minecraft:stone_button",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Trigger"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:carrot_on_a_stick,Count:1,Damage:7,tag:{Unbreakable:1,display:{Name:"§4Laser Rifle"}}}]}

#gun - rail gun
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:3b,id:"minecraft:wool",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Stock"}},Damage:0s},{Slot:4b,id:"minecraft:redstone_block",Count:16b,Damage:0s},{Slot:5b,id:"minecraft:stick",Count:1b,tag:{ench:[{lvl:2,id:48}],display:{Lore:["A gun part."],Name:"Laser Gun Barrel"}},Damage:0s},{Slot:6b,id:"minecraft:dropper",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Magazine Chamber"}},Damage:0s},{Slot:7b,id:"minecraft:stone_button",Count:1b,tag:{ench:[{lvl:1,id:48}],display:{Lore:["A gun part."],Name:"Trigger"}},Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:carrot_on_a_stick,Count:1,Damage:8,tag:{Unbreakable:1,display:{Name:"§2Rail Gun"}}}]}


#### random gadgets ####
#super booster
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:1b,id:"minecraft:firework_charge",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:paper",Count:3b,Damage:0s},{Slot:6b,id:"minecraft:gunpowder",Count:3b,Damage:0s},{Slot:7b,id:"minecraft:gunpowder",Count:3b,Damage:0s},{Slot:8b,id:"minecraft:gunpowder",Count:3b,Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:fireworks,Count:3,tag:{Fireworks:{Flight:50},display:{Name:"§cSuper Booster"}}}]}

#ender? pearl
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:0b,id:"minecraft:dragon_breath",Count:1b,Damage:0s},{Slot:1b,id:"minecraft:dragon_breath",Count:1b,Damage:0s},{Slot:2b,id:"minecraft:dragon_breath",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:ender_eye",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:ender_pearl",Count:4b,Damage:0s},{Slot:5b,id:"minecraft:ender_eye",Count:1b,Damage:0s},{Slot:6b,id:"minecraft:dragon_breath",Count:1b,Damage:0s},{Slot:7b,id:"minecraft:dragon_breath",Count:1b,Damage:0s},{Slot:8b,id:"minecraft:dragon_breath",Count:1b,Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:ender_pearl,Count:4,tag:{ench:[{id:51,lvl:1}],display:{Name:"§5§kEnder§r§5 Pearl"}}}]}

#gas grenade
execute @s ~ ~ ~ testforblock ~ ~-1 ~ minecraft:dispenser 1 {Items:[{Slot:1b,id:"minecraft:potion",Count:1b,tag:{Potion:"minecraft:water"},Damage:0s},{Slot:3b,id:"minecraft:fish",Count:4b,Damage:3s},{Slot:4b,id:"minecraft:fermented_spider_eye",Count:4b,Damage:0s},{Slot:5b,id:"minecraft:spider_eye",Count:4b,Damage:0s},{Slot:6b,id:"minecraft:dragon_breath",Count:4b,Damage:0s},{Slot:7b,id:"minecraft:nether_wart",Count:4b,Damage:0s},{Slot:8b,id:"minecraft:dragon_breath",Count:4b,Damage:0s}]}
execute @s[score_checks_min=1] ~ ~ ~ blockdata ~ ~-1 ~ {Items:[{Slot:4,id:lingering_potion,Count:1b,tag:{display:{Name:"§8Gas Grenade"},CustomPotionEffects:[{Id:4,Amplifier:0,Duration:200,ShowParticles:0b},{Id:15,Amplifier:0,Duration:200,ShowParticles:0b},{Id:18,Amplifier:0,Duration:200,ShowParticles:0b},{Id:20,Amplifier:1,Duration:200,ShowParticles:0b}],Potion:"minecraft:long_slowness"}}]}

