summon boat ~ ~500 ~ {Tags:["b1","proj","newProj"],NoGravity:1b,Type:"oak",Passengers:[{id:"armor_stand",Tags:["s1","proj"],NoGravity:1b},{id:"armor_stand",Tags:["s2","proj"],NoGravity:1b}]}
teleport @e[tag=newProj] ~ ~500 ~ ~180 ~
scoreboard players set @e[tag=newProj] timer 0

execute @s[rx=-60,rxm=-89] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -60
execute @s[rx=-59,rxm=-60] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -59
execute @s[rx=-58,rxm=-59] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -58
execute @s[rx=-57,rxm=-58] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -57
execute @s[rx=-56,rxm=-57] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -56
execute @s[rx==55,rxm=-56] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -55
execute @s[rx=-54,rxm=-55] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -54
execute @s[rx=-53,rxm=-54] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -53
execute @s[rx=-52,rxm=-53] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -52
execute @s[rx=-51,rxm=-52] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -51
execute @s[rx=-50,rxm=-51] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -50
execute @s[rx=-49,rxm=-50] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -49
execute @s[rx=-48,rxm=-49] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -48
execute @s[rx=-47,rxm=-48] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -47
execute @s[rx=-46,rxm=-47] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -46
execute @s[rx=-45,rxm=-46] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -45
execute @s[rx=-44,rxm=-45] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -44
execute @s[rx==43,rxm=-44] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -43
execute @s[rx=-42,rxm=-43] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -42
execute @s[rx=-41,rxm=-42] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -41
execute @s[rx=-40,rxm=-41] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -40
execute @s[rx=-39,rxm=-40] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -39
execute @s[rx=-38,rxm=-39] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -38
execute @s[rx=-37,rxm=-38] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -37
execute @s[rx=-36,rxm=-37] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -36
execute @s[rx=-35,rxm=-36] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -35
execute @s[rx=-34,rxm=-35] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -34
execute @s[rx=-33,rxm=-34] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -33
execute @s[rx=-32,rxm=-33] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -32
execute @s[rx=-31,rxm=-32] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -31
execute @s[rx=-30,rxm=-31] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -30
execute @s[rx=-29,rxm=-30] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -29
execute @s[rx=-28,rxm=-29] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -28
execute @s[rx=-27,rxm=-28] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -27
execute @s[rx=-26,rxm=-27] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -26
execute @s[rx=-25,rxm=-26] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -25
execute @s[rx=-24,rxm=-25] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -24
execute @s[rx=-23,rxm=-24] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -23
execute @s[rx=-22,rxm=-23] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -22
execute @s[rx=-21,rxm=-22] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -21
execute @s[rx=-20,rxm=-21] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -29
execute @s[rx=-19,rxm=-20] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -19
execute @s[rx=-18,rxm=-19] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -18
execute @s[rx=-17,rxm=-18] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -17
execute @s[rx=-16,rxm=-17] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -16
execute @s[rx=-15,rxm=-16] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -15
execute @s[rx=-14,rxm=-15] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -14
execute @s[rx=-13,rxm=-14] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -13
execute @s[rx=-12,rxm=-13] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -12
execute @s[rx=-11,rxm=-12] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -11
execute @s[rx=-1,rxm=-11] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -10
execute @s[rx=-9,rxm=-10] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -9
execute @s[rx=-8,rxm=-9] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -8
execute @s[rx=-7,rxm=-8] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -7
execute @s[rx=-6,rxm=-7] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -6
execute @s[rx=-5,rxm=-6] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -5
execute @s[rx=-4,rxm=-5] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -4
execute @s[rx=-3,rxm=-4] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -3
execute @s[rx-2=,rxm=-3] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -2
execute @s[rx=-1,rxm=-2] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX -1
execute @s[rx=1,rxm=-1] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 0
execute @s[rx=2,rxm=1] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 1
execute @s[rx=3,rxm=2] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 2
execute @s[rx=4,rxm=3] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 3
execute @s[rx=5,rxm=4] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 4
execute @s[rx=6,rxm=5] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 5
execute @s[rx=7,rxm=6] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 6
execute @s[rx=8,rxm=7] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 7
execute @s[rx=9,rxm=8] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 8
execute @s[rx=10,rxm=9] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 9
execute @s[rx=11,rxm=10] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 10
execute @s[rx=12,rxm=11] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 11
execute @s[rx=13,rxm=12] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 12
execute @s[rx=14,rxm=13] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 13
execute @s[rx=15,rxm=14] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 14
execute @s[rx=16,rxm=15] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 15
execute @s[rx=17,rxm=16] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 16
execute @s[rx=18,rxm=17] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 17
execute @s[rx=19,rxm=18] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 18
execute @s[rx=20,rxm=19] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 19
execute @s[rx=21,rxm=20] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 20
execute @s[rx=22,rxm=21] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 21
execute @s[rx=23,rxm=22] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 22
execute @s[rx=24,rxm=23] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 23
execute @s[rx=25,rxm=24] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 24
execute @s[rx=26,rxm=25] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 25
execute @s[rx=27,rxm=26] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 26
execute @s[rx=28,rxm=27] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 27
execute @s[rx=29,rxm=28] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 28
execute @s[rx=30,rxm=29] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 29
execute @s[rx=31,rxm=30] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 30
execute @s[rx=32,rxm=31] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 31
execute @s[rx=33,rxm=32] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 32
execute @s[rx=34,rxm=33] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 33
execute @s[rx=35,rxm=34] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 34
execute @s[rx=36,rxm=35] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 35
execute @s[rx=37,rxm=36] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 36
execute @s[rx=38,rxm=37] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 37
execute @s[rx=39,rxm=38] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 38
execute @s[rx=40,rxm=39] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 39
execute @s[rx=41,rxm=40] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 40
execute @s[rx=42,rxm=41] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 41
execute @s[rx=43,rxm=42] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 42
execute @s[rx=44,rxm=43] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 43
execute @s[rx=45,rxm=44] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 44
execute @s[rx=46,rxm=45] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 45
execute @s[rx=47,rxm=46] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 46
execute @s[rx=48,rxm=47] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 47
execute @s[rx=49,rxm=48] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 48
execute @s[rx=50,rxm=49] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 49
execute @s[rx=51,rxm=50] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 50
execute @s[rx=52,rxm=51] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 51
execute @s[rx=53,rxm=52] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 52
execute @s[rx=54,rxm=53] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 53
execute @s[rx=55,rxm=54] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 54
execute @s[rx=56,rxm=55] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 55
execute @s[rx=57,rxm=56] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 56
execute @s[rx=58,rxm=57] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 57
execute @s[rx=58,rxm=58] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 58
execute @s[rx=60,rxm=59] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 59
execute @s[rx=89,rxm=60] ~ ~ ~ scoreboard players set @e[tag=newProj,c=1] rotX 60

scoreboard players tag @e[tag=newProj] remove newProj